/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtistCard: typeof import('./../frontend/components/artist-card.vue')['default']
    DefaultHeader: typeof import('./../frontend/components/default-header.vue')['default']
    FormLabel: typeof import('./../frontend/components/form-label.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDynamicInput: typeof import('naive-ui')['NDynamicInput']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PlayerBar: typeof import('./../frontend/components/player-bar.vue')['default']
    README: typeof import('./../frontend/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerBackendOperation: typeof import('./../frontend/components/server-backend-operation.vue')['default']
    SkeletonImage: typeof import('./../frontend/components/skeleton-image.vue')['default']
    SongListCard: typeof import('./../frontend/components/song-list-card.vue')['default']
    SongListItem: typeof import('./../frontend/components/song-list-item.vue')['default']
  }
}
