/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/artist/[id]': RouteRecordInfo<'/artist/[id]', '/artist/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/my': RouteRecordInfo<'/my', '/my', Record<never, never>, Record<never, never>>,
    '/play-list/[id]': RouteRecordInfo<'/play-list/[id]', '/play-list/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/setting': RouteRecordInfo<'/setting', '/setting', Record<never, never>, Record<never, never>>,
  }
}
